# Generated by Django 2.1 on 2019-08-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=150)),
                ('lname', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('Cemail', models.EmailField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('Cpassword', models.CharField(max_length=150)),
            ],
        ),
    ]
